# Generated by Django 5.0.7 on 2024-08-10 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoItem',
            new_name='Todo',
        ),
    ]
